### ISSUE TITLE
Create an R package to handle CFF 

### ISSUE THREAD

**Issue by wleoncio** [citation-file-format/citation-file-format#110]
# Summary

Proposal for creating an R package that inputs from/outputs to CITATION.cff (tentative name: RCFF)

# Motivation

The metadata for [R](https://cran.r-project.org/) packages are contained within a [DESCRIPTION file](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file), and I would like to create an R package to handle the translation between that format and the CFF. I couldn't find anything about this on this Issues page (hopefully it's the right place to look), so was wondering if there is anyone already working on it and what the CFF authors think about the idea. I, for one, think this could be a great asset in helping CFF establish itself as the _de facto_ standard for research software citation.

R is very popular in academia, and it does have a base function called `citation()` that reads from a package metadata and prints citations in APA-like and Bibtex formats, as per the following example:

```
> citation("stats")

The ‘stats’ package is part of R.  To cite R in publications use:

  R Core Team (2020). R: A language and environment for statistical
  computing. R Foundation for Statistical Computing, Vienna, Austria.
  URL https://www.R-project.org/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {R: A Language and Environment for Statistical Computing},
    author = {{R Core Team}},
    organization = {R Foundation for Statistical Computing},
    address = {Vienna, Austria},
    year = {2020},
    url = {https://www.R-project.org/},
  }

We have invested a lot of time and effort in creating R, please cite it
when using it for data analysis. See also ‘citation("pkgname")’ for
citing R packages.
```

This covers the two most popular cases in academia, but I think it's missing an output to a more unversal format such as the CFF. Even within the R world, a CITATION.cff would be useful for non-packaged software such as scripts and Shiny apps.

An alternative to creating a package is to try to convince upstream R developers to extend the `citation()` function, but even if they agree to that, it wouldn't cover the "import from CFF" feature (or any other we might decide to implement along the process).

# Repository location

Given how the [PyCFF repository](https://github.com/citation-file-format/pycff) is part of the citation-file-format organization, I was wondering if an RCFF package should also be hosted there (an alternative would be for me to host it on [my organization's page](https://github.com/ocbe-uio).

**Comment by sdruskat** [comment]
Hi @wleoncio, thanks for the proposal. I don't know that anyone is working on this yet. I think it would be a fantastic project! I also don't see a reason why this shouldn't be hosted in the CFF org.

I'm currently on holidays until mid July. Let me get back to you more comprehensively after then? If you want to start this elsewhere already, we can always transfer the repo later. 

Thanks!

**Comment by wleoncio** [comment]
Thank you for the greenlight, @sdruskat! No rush on my part, I'm out on a short vacation absence myself next week, so we can pick this up after you're back. If I get too antsy, I'll start a local repo (or upload and transfer later, as you wrote).

Cheers,
Waldir

**Comment by mariabnd** [comment]
Hi @wleoncio, are you still working on this? If so, I'm happy to help where I can.

**Comment by wleoncio** [comment]
Hi @mariabnd, thank you for showing interest in the project. I got a bit of groundwork done while I was waiting for @sdruskat's follow up. Then other projects got in the way, so an extra set of hands and brains is very welcome.

If we get a greenlight from the CFF team (particularly regarding where on GitHub the project will be hosted), I'll push my local repo so you can take a look at it.

Happy holidays to all!

**Comment by sdruskat** [comment]
Hi @wleoncio, really sorry for the delay in replying. Don't have much bandwidth at the moment.

To get this underway, would you be happy to host under your GitHub org, and we'll link to it from here, as a first step?
I'd like to bring it into this org, but need more time to figure out how to best do this.
Thanks!

**Comment by wleoncio** [comment]
> To get this underway, would you be happy to host under your GitHub org, and we'll link to it from here, as a first step?

Sure thing, @sdruskat! I'll set things up (repo, link here, add @mariabnd as external collaborator to my org) ASAP, likely before the end of the week.

**Comment by wleoncio** [comment]
To get things rolling, I've created https://github.com/ocbe-uio/RCFF and pushed most of my commits there (the only thing I didn't push is a branch where I started to implement some S4 classes, but that will probably go stale and be dropped due to it making things more complicated than they need to be).

At this point I don't think there are enough features to even consider this on "alpha" stage, but the package _is_ technically installable and usable. As proof-of-concept, there's a function in there called `r2cff()` to (half-assedly) convert a package's title and version number from the "R DESCRPTION format" to CFF. I've also [created a couple of issues](https://github.com/ocbe-uio/RCFF/issues) to remind myself to polish all the hastly-coded things I wrote just to make this minimally presentable. 

@mariabnd, how is your current availability to contribute? Times are tough for everybody. I, for one, am on partial parental leave, so my working hours are limited and I must prioritize other software over this, but I am really glad this is out so it stares at my face more prominently.

**Comment by mariabnd** [comment]
@wleoncio things are a bit hectic here too, but I hope to take a look over the weekend

**Comment by jmcastagnetto** [comment]
I was looking for an R package that could deal with CFF files, and found this thread, among other results. You might be interested in the {citation} package that is in CRAN https://cran.r-project.org/web/packages/citation/ (https://github.com/pik-piam/citation), seems to have support to generate CFF files from the DESCRIPTION file of a package.

Also, the `utils::citation()` function parses the DESCRIPTION file into something that can be easily manipulated, and converted into other format.

**Comment by mariabnd** [comment]
@wleoncio Did you see this from a few days ago? https://twitter.com/natfriedman/status/1420122675813441540

**Comment by jmcastagnetto** [comment]
@mariabnd, that was my motivation to check for a package to generate CFF files :-)

**Comment by sdruskat** [comment]
I'll add the `help wanted` label to this issue. Let me know if you'd rather have it removed again, just thought that it may help to attract more contributions.

**Comment by wleoncio** [comment]
@jmcastagnetto, @mariabnd and @sdruskat, thank you for the messages. I've just came back from vacation (literally 20 minuts ago), but I'll take a carefull look at these references ASAP to see what's the most sensible course of action (merge [RCPP](https://github.com/ocbe-uio/RCFF), keep it as a separate package or drop it altogether).

**Comment by dieghernan** [comment]
See an example, this have been generated automatically by **cffr**:

```

cff-version: 1.2.0
message: 'To cite package "cffr" in publications use:'
type: software
license: GPL-3.0-or-later
title: 'cffr: Generate Citation File Format (''cff'') Metadata for R Packages'
version: 0.0.0.9000
abstract: The Citation File Format (version 1.2.0) <doi:10.5281/zenodo.5171937> is
  a human and machine readable file format which provides citation metadata for software.
  This package provides core utilities to generate and validate this metadata.
authors:
- family-names: Hernangómez
  given-names: Diego
  email: diego.hernangomezherrero@gmail.com
  orcid: https://orcid.org/0000-0001-8457-4658
preferred-citation:
  title: 'cffr: Generate Citation File Format (''cff'') Metadata for R Packages'
  authors:
  - family-names: Hernangómez
    given-names: Diego
  year: '2021'
  url: https://dieghernan.github.io/cffr/
  type: manual
repository-code: https://github.com/dieghernan/cffr
url: https://dieghernan.github.io/cffr/
contact:
- family-names: Hernangómez
  given-names: Diego
  email: diego.hernangomezherrero@gmail.com
  orcid: https://orcid.org/0000-0001-8457-4658
keywords:
- attribution
- citation
- credit
- citation-files
- cff
- metadata

```
