### ISSUE TITLE
Create `role` as a simple way to record contribution roles?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#112]
Just dropping this as an idea I just had: We could add `role`/`roles` to person/entity/the new umbrella object to provide a simple, works-now solution for recording contribution roles for people/institutions (this would open CFF up to recording funding as well for example).

This isn't ready to go I think, still need to check it against the other plans for CFF.

**Comment by jspaaks** [comment]
Related: https://github.com/citation-file-format/citation-file-format/issues/84, https://github.com/citation-file-format/citation-file-format/issues/27

**Comment by jcolomb** [comment]
Hello,
you may want to have a look at our work at https://github.com/jam-schema/jams

Our main focus has been to get all authors information available in jatsxml (research papers standard) into a yaml format. Apart from issues with  author that are groups of people, we have covered a lot of cases, including how to define roles. 

role:
      vocab-term-identifier: free text explanation
      
This is mostly meant to be used with the CREDIT taxonomy, but for the off purpose, one should probably look at other taxonomies (all-contributors or [CRO](https://bioportal.bioontology.org/ontologies/CRO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCRO_0000060)


@arfon : you probably would be the best person to see how the projects could interact ?

**Comment by arfon** [comment]
> @arfon : you probably would be the best person to see how the projects could interact ?

Yup, happy to try and assist with coordination here. @sdruskat – is adding contributor roles something you're still interested in?

**Comment by sdruskat** [comment]
Yes, still interested! I'll try and pick this up next week when I'm back from leave.

**Comment by sdruskat** [comment]
Related: https://upstream.force11.org/posts/deep-dive-into-ethics-of-contributor-roles

This will still take some time due to other responsiblities.

**Comment by jcolomb** [comment]
related:https://demo.hedgedoc.org/WWA2OwbbSeiVXkTkLSwadA

**Comment by 1kastner** [comment]
This sounds very interesting indeed!

**Comment by sdruskat** [comment]
Also related, an initial crosswalk for contributor roles by Ted Habermann: https://zenodo.org/record/4767798.

**Comment by kevinmatthes** [comment]
Related:  https://github.com/all-contributors/all-contributors/issues/664

**Comment by kevinmatthes** [comment]
I would like to suggest to make the `roles` field an array of strings in order to support best the possibilities of the All Contributors bot.

**Comment by jcolomb** [comment]
great idea @kevinmatthes, also related to https://github.com/all-contributors/all-contributors/issues/471.
Contribution would make most sense if it can be taken up by zenodo (zenodo has roles for contributors, not for authors. the roles listed are (I think) a home-made list not related to CREDIT or contributor bot.

all coming to building a standard way to design authors and contribution, right? maybe you want to join the jams mini-community: https://github.com/jam-schema/jams/issues/7

**Comment by sdruskat** [comment]
@kevinmatthes Thanks. Yes, I think having `roles` be plural and provide an array of strings is a good start. Ideally I would like this to be an enum, but the lack of agreement on what the values would have to be, i.e., the standard vocabulary for software contribution roles, is work in progress it seems.

@jcolomb I never found the time to engage with JAMS 😢, but is building this (sub-)vocabulary in the scope of JAMS?

**Comment by jcolomb** [comment]
no, "building this (sub-)vocabulary" is more a work for NISO/FORCE11 
but jams is looking for technical ways to use different vocabularies, people tend to think about ontologies when we present the problem(s).

**Comment by jcolomb** [comment]
They use the CRO ontology in their example, also think the people behind are also behind CRO (Melissa heandel and co). (CRO behind the extension of CREDIT) you may want to see https://doi.org/10.1002/leap.1496 for discussions about these vocabularies development.

**Comment by apirogov** [comment]
I'd also be happy to have some `roles` concept, to distinguish "main authors" from "acknowledged contributors" 

I'd also like to have an optional free-text field to state the actual main contribution(s) of each mentioned person, because in the end, any fixed "vocabulary" will be not expressive enough and I think a "who did what" list deserves at least some semi-structured form of being expressed.

**Comment by dmoracze** [comment]
+1 on creating a way to denote contribution type. 
And I'll echo the suggestion that takes advantage of the work already done by the CRediT team: https://credit.niso.org/ 
What about a solution that looks something like:
```
authors:
  - given-names: Author
    family-names: One
    affiliation: Institute
    orcid: 'https://orcid.org/0000-0000-0000-0000'
    contribution:
      - role: Conceptualization
        credit-id: '8b73531f-db56-4914-9502-4cc4d4d8ed73'
      - role: Formal analysis
        credit-id: '8b73531f-db56-4914-9502-4cc4d4d8ed73'
      - role: Writing - original draft
        credit-id: '43ebbd94-98b4-42f1-866b-c930cef228ca'
  - given-names: Author
    family-names: Two
    affiliation: Institute
    orcid: 'https://orcid.org/0000-0000-0000-0001'
    contribution:
      - role: Data curation
        credit-id: 'f93e0f44-f2a4-4ea1-824a-4e0853b05c9d'
  - given-names: Author
    family-names: Three
    affiliation: Institute
    orcid: 'https://orcid.org/0000-0000-0000-0002'
    contribution:
      - role: Funding acquisition
        credit-id: '34ff6d68-132f-4438-a1f4-fba61ccf364a'
      - role: Conceptualization
        credit-id: '8b73531f-db56-4914-9502-4cc4d4d8ed73'
      -role: Writing - review & editing
        credit-id: 'd3aead86-f2a2-47f7-bb99-79de6421164d'
```

**Comment by sdruskat** [comment]
Thanks, @dmoracze, for your comment. Contribution roles are planned to be part of the next minor release (1.3.0).

We're vetting different taxonomies for software contributions. CRediT has exactly one [software role](https://credit.niso.org/contributor-roles/software/), so we likely won't use this taxonomy as is. In [other work](https://sdruskat.net/software-authorship/) (v. early draft!), we've started looking at harmonizing taxonomies. We may use the outputs of this work, as it also seeks support from community initiatives.

**Comment by dmoracze** [comment]
Sounds good, @sdruskat! I look forward to it.

**Comment by effigies** [comment]
We're looking into using `CITATION.cff` to describe datasets, rather than software, and we register these datasets for DOIs using DataCite. To the extent that roles can correspond with DataCite's [`contributorType`](https://support.datacite.org/v1.3/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#7a-contributortype), we will be able to more faithfully map uploader intent onto DOI metadata.

I'm quite sure you've seen it, but figured I'd link it into this thread.

Another resource that might be useful for the dataset use case is the schema used by the DANDI archive, which includes EthicsApproval and Maintainer, neither of which show up in Credit or DataCite: https://github.com/dandi/schema/blob/1866f4d/releases/0.6.4/dandiset.json#L246-L278.

**Comment by ericearl** [comment]
I tried to apply something close to @dmoracze 's solution here, and it occurred to me there are so many competing standards for what roles or contributions should be called or should look like. Would it be reasonable to allow something more basic with no ontologies or exact options behind it like just a free text unordered list? You can simply enforce it's a list this way. Something like `roles` or `contributions` like this:

```yaml
  - given-names: Eric
    family-names: Earl
    affiliation: >-
      Data Science & Sharing Team, National Institute of
      Mental Health, Bethesda, MD, USA
    orcid: https://orcid.org/0000-0001-5512-0083
    contributions:
        - Data curation
```

Thank you all for your involvement and consideration here!
