### ISSUE TITLE
How to handle name changes

### ISSUE THREAD

**Issue by dschwoerer** [citation-file-format/citation-file-format#255]
I have been wondering how should name changes be reflected in the CFF format.

Say my family-name changes from "A" to "B". Is there a clean way to include both in the CFF format?

The [documenation](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#exemplary-uses-2) mention that `family-names` can be double names, thus adding both old and new name could be mistaken for a double name.

**Comment by jspaaks** [comment]
Hi @dschwoerer, and welcome to the project. I am not aware of any ongoing or past discussions that cover the use case you describe-- `family-names` was indeed intended to include double or even more names, but not name changes. Perhaps this is already desired behavior for the format, because one could argue that at the time of a release / publication, each author has one name, either "A" or "B", but not both. I'm guessing the closest thing is to use `alias`, like so:

```yaml
authors:
  - 
    alias: A
    family-names: B
```

although a more typical use case for `alias` would be something like:

```yaml
authors:
  - 
    alias: jspaaks
    family-names: Spaaks
    given-names: "Jurriaan H."
```
