### ISSUE TITLE
Your CITATION.cff file cannot be parsed. Make sure the formatting is correct

### ISSUE THREAD

**Issue by nschloe** [citation-file-format/citation-file-format#260]
I just added a CITATION.cff to one of my GitHub repos to try it out (https://github.com/nschloe/meshio/blob/main/CITATION.cff).
```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Schlömer
    given-names: Nico
    orcid: "https://orcid.org/0000-0001-5228-0946"
title: "meshio"
doi: 10.5281/zenodo.1173115
url: "https://github.com/nschloe/meshio"
```
Unfortunately, I'm getting the error message
```
Your CITATION.cff file cannot be parsed. Make sure the formatting is correct. Learn more.
```
Any hint on what's wrong?
