### ISSUE TITLE
Protect case of proper names

### ISSUE THREAD

**Issue by jedbrown** [citation-file-format/citation-file-format#269]
There does not seem to be a convention for protecting case of proper names so you see
```
title: "XYZ: An ABC alternative"
```
produces the BibTeX
```
title={XYZ: An ABC alternative}
```
which will lose its case when reduced to sentence case by biblatex or pandoc-citeproc. One can hack this for BibTeX (at least as formatted on GitHub citations) using
```
title: "{XYZ}: An {ABC} alternative"
```
but the APA citation and BibTeX key come out mangled. Some convention (could be BibTeX's) should be specified and GitHub's test suite should include this case. (I don't know how closely members of this project might work with the GitHub folks that deployed the sidebar feature, but they don't have a place to file bug reports.)

**Comment by jspaaks** [comment]
(Just making a note here of a not fully fledged idea to be considered later, I'm guessing at least after 1.2.0)

I see two routes to do this:
1. make the casing part of `title`'s value, like with bibtex braces
2. create a new, dedicated field, for example `title-casing`

If we do decide to use the 2nd option, maybe we could have something like

```yaml
references:
  - type: generic
    title:        "ruby-cff: A Ruby library for manipulating CITATION.cff files"
    title-casing: "llll.lll....ulll..........................uuuuuuuu.lll......"
```

where the author of the `CITATION.cff` file can specify how they intended casing (`l`: lowercase, `u`: uppercase, `.`: let downstream tooling decide)

With this setup, there would be enough information for BibTeX/APA generators like `ruby-cff` or `cffconvert`, e.g. to wrap substrings whose casing should be protected in curly braces, something like:

```text
{{ruby}-{cff}: A {Ruby} library for manipulating {CITATION}.{cff} files}
```
, without contaminating the metadata with markup.

**Comment by hainesr** [comment]
How about a combination of 1 and 2? So have a field such as `title-casing` but use markup instead:
```yaml
references:
  - type: generic
    title:        "ruby-cff: A Ruby library for manipulating CITATION.cff files"
    title-casing: "{ruby-cff}: A {Ruby} library for manipulating {CITATION.cff} files"
```
You can still see which regions need to be protected; if you need to see which characters need to be upper/lower case you can look at them; and it's (probably) easier to spot if the two strings get out of sync.

I have to say I don't think there's a neat solution to this, BTW 😞
