### ISSUE TITLE
schema: all numbers are also valid as string, but integers arent

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#271]
For example, users can write their `version` as a YAML number (e.g. `1.2` or `20190328`)  or as YAML string (e.g. `1.12.3` or `"1.2"`) using this part of the schema:

```yaml
"version": {
    "anyOf": [
        {
            "minLength": 1,
            "type": "string"
        },
        {
            "type": "number"
        }
    ]
```

but for fields of type `integer`, this isn't done consistently. For example, one can write:
```yaml
references:
  - type: generic
    start: 100
```

but not:

```yaml
references:
  - type: generic
    start: "100"
```

even though it is unambiguous. 

I think we should consider treating the remaining `type: integer`s the same as `type: number`s. I see at least 2 advantages of doing so:
1. additional leniency makes users' lives easier: if we allow strings for `type integer`s, that means that users dont have to think about / look up what the expected type is, since they can count on all primitive-type fields at least (also) being a string
3. Any downstream tooling can internally cast to string and still have file contents that are valid according to the schema. I don't think there are any downsides to doing so, because as far as I'm aware there are no tools that depend on integer logic on the user inputs to accomplish their goals.

The affected keys are:

1. `reference.end`
1. `reference.loc-end`
1. `reference.loc-start`
1. `reference.month`
1. `reference.number-volumes`
1. `reference.pages`
1. `reference.start`
1. `reference.volume`
1. `reference.year`
1. `reference.year-original`

Perhaps there are other concerns though, happy to hear them
