### ISSUE TITLE
"Conference" field does not appear in APA or Bibtex

### ISSUE THREAD

**Issue by remram44** [citation-file-format/citation-file-format#317]
## `CITATION.cff` file

My preferred-citation is a conference proceedings:

```yaml
preferred-citation:
  type: proceedings
  doi: 10.1145/2882903.2899401
  conference:
    name: "SIGMOD '16"
    website: https://www.sigmod2016.org/
    city: San Francisco
    country: US
  authors:
    - family-names: Rampin
      given-names: Remi
      affiliation: New York University
      orcid: https://orcid.org/0000-0002-0524-2282
      website: https://remi.rampin.org/
    - family-names: Freire
      given-names: Juliana
      affiliation: New York University
      orcid: https://orcid.org/0000-0003-3915-7075
      website: https://vgc.poly.edu/~juliana/
    - family-names: Chirigati
      given-names: Fernando
      affiliation: New York University
      orcid: https://orcid.org/0000-0002-9566-5835
      website: http://fchirigati.com/
    - family-names: Shasha
      given-names: Dennis
      affiliation: New York University
      orcid: https://orcid.org/0000-0002-7036-3312
      website: http://cs.nyu.edu/shasha/
  date-published: 2016-06-26
  year: 2016
  month: 6
  title: "ReproZip: Computational Reproducibility With Ease"
```

Somehow this gets [rendered on GitHub](https://github.com/VIDA-NYU/reprozip/tree/0f9fd1d17485df20b3c24cbf842db5d48aa9224a) as:

Rampin, R., Freire, J., Chirigati, F., & Shasha, D. (2016). ReproZip: Computational Reproducibility With Ease. https://doi.org/10.1145/2882903.2899401

```
@proceedings{Rampin_ReproZip_Computational_Reproducibility_2016,
    author = {Rampin, Remi and Freire, Juliana and Chirigati, Fernando and Shasha, Dennis},
    doi = {10.1145/2882903.2899401},
    month = {6},
    title = {{ReproZip: Computational Reproducibility With Ease}},
    year = {2016}
}
```

As you can see only the title is there, which makes for a very awkward citation.

# Context

I am trying to make a CFF equivalent to [the existing CITATION.txt](https://github.com/VIDA-NYU/reprozip/blob/0f9fd1d17485df20b3c24cbf842db5d48aa9224a/CITATION.txt):

```
To reference ReproZip in publications, please cite the following:

ReproZip: Computational Reproducibility With Ease, F. Chirigati, R. Rampin, D. Shasha, and J. Freire. In Proceedings of the 2016 ACM SIGMOD International Conference on Management of Data (SIGMOD), pp. 2085-2088, 2016

BibTeX:

@inproceedings{ChirigatiRSF16,
  title = {ReproZip: Computational Reproducibility With Ease},
  author = {Chirigati, Fernando and Rampin, R{\'e}mi and Shasha, Dennis and Freire, Juliana},
  year = {2016},
  isbn = {978-1-4503-3531-7},
  location = {San Francisco, California, USA},
  doi = {10.1145/2882903.2899401},
  booktitle = {Proceedings of the 2016 International Conference on Management of Data},
  series = {SIGMOD '16},
  pages = {2085--2088},
  numpages = {4},
  publisher = {ACM},
  keywords = {computational reproducibility, provenance, reprozip},
}
```
