### ISSUE TITLE
Why are some strings quoted?

### ISSUE THREAD

**Issue by edent** [citation-file-format/citation-file-format#322]
In the examples, some strings are quoted, and some aren't:

```
authors:
  - family-names: Druskat
    given-names: Stephan
    name-particle: von
    name-suffix: III
    address: "742 Evergreen Terrace"
    affiliation: "German Aerospace Center (DLR)"
    alias: "sdruskat"
    city: "Berlin"
    country: "DE"
    email: "sdruskat@research-project.org"
    fax: +12-3456-7890
    orcid: "https://orcid.org/0000-0003-4925-7248"
    post-code: 90210
    region: Renfrewshire
    tel: +12-345-6789098
    website: "https://research-project.org"
  ```
and

```
abstract: This is my awesome research software. It does many things.
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: "https://orcid.org/0000-0003-4925-7248"
cff-version: 1.2.0
date-released: "2021-07-18"
identifiers:
  - description: This is the collection of archived snapshots of all versions of My Research Software
    type: doi
    value: 10.5281/zenodo.123456
  - description: This is the archived snapshot of version 0.11.2 of My Research Software
    type: doi
    value: 10.5281/zenodo.123457
keywords:
  - "awesome software"
  - research
license: Apache-2.0
message: If you use this software, please cite it using these metadata.
repository-code: "https://github.com/citation-file-format/my-research-software"
title: My Research Software
version: 0.11.2
```
What's the logic behind which strings are quoted and which aren't? Some strings with spaces are quoted, some aren't. `date-released:` sometimes has them, sometimes not.

Is there a simple guide to which ones need to be quoted? Would it make sense to wrap *all* values in quotes in the examples?
