### ISSUE TITLE
cffinit website should validate its own output

### ISSUE THREAD

**Issue by bielsnohr** [citation-file-format/citation-file-format#325]
I recently went through the process of generating a `CITATION.cff` file for one of my repositories, and one major pain point was that the file produced by the [cffinit](https://citation-file-format.github.io/cff-initializer-javascript/) tool was not valid and caused both GitHub and Zenodo to fall over. My expectation was that the tool would self-validate its output. Alternatively, as a stop-gap, there should be a fairly obvious disclaimer that all files should be validated before using them in GitHub and Zenodo.

**Comment by jspaaks** [comment]
Hi @bielsnohr,
thanks for reporting the issue. Can you provide the `CITATION.cff` text that was giving you trouble so I can have a look?

**Comment by sdruskat** [comment]
Perhaps the current `cffinit` website should have a wee warning bar that says it only supports `1.1.0` while that's true?

**Comment by bielsnohr** [comment]
@jspaaks this is the offending file that I produced directly from `cffinit`

```
# YAML 1.2
---
authors: 
  -
    affiliation: UKAEA
    family-names: Bluteau
    given-names: Matthew
    orcid: "https://orcid.org/0000-0001-9498-8475"
  -
    affiliation: UKAEA
    family-names: Gadgil
    given-names: Sanket
  -
    affiliation: "Brookhaven National Laboratory"
    family-names: 
    given-names: 
cff-version: "1.1.0"
date-released: 2021-08-24
license: "BSD-3-Clause"
message: "If you would like to reference the tutorial or cookiecutter template, please cite them using these metadata."
title: "UKAEA Scientific Python Cookiecutter"
version: "v1.0.0"
... 
```

The problem of course is that the names for the third author entry are empty. However, for someone unfamiliar with cff and who only uses YAML occasionally, the fact that this isn't valid is not obvious initially.

Also, perhaps this issue should be moved to the `cffinit` repo? I didn't see it when submitting the issue.
