### ISSUE TITLE
New GitHub Action released: cff-validator

### ISSUE THREAD

**Issue by dieghernan** [citation-file-format/citation-file-format#340]
### Who needs the new tool?

Any user of `CITATION.cff` files.

### What should the new tool enable users to do?

I want to validate on the fly my `CITATION.cff` files hosted on GitHub.

### What benefit would the new tool add?

Users will be able to ensure that their CITATION files are correct as per the schema.

### Implementation suggestions

I already implemented a GitHub Action: <https://github.com/marketplace/actions/cff-validator>.

This is based on **R** software, and on error provides the user with messages regarding the root cause of the error.

Note that it has been already [validated](https://github.com/dieghernan/cff-validator/actions) against a [fully loaded CITATION.cff file](https://github.com/dieghernan/cff-validator/blob/main/examples/CITATION_full.cff) (163 lines) based on the examples provided on the [schema guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md).

### Can you help?

- [x] Yes
- [ ] No

If you consider that this action is useful I would suggest to include it on the [Tooling](https://github.com/citation-file-format/citation-file-format#tools-to-work-with-citationcff-files-wrench) section of the README file.

See a full implementation of a GitHub Action below:

```yaml

on:
  push:
    paths:
      - CITATION.cff
    workflow_dispatch:

name: CITATION.cff
jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This is needed for workflows running on
      # ubuntu-20.04 or later
      - name: Install V8
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libv8-dev
      - name: Validate CITATION.cff
        uses: dieghernan/cff-validator@v1

```
