### ISSUE TITLE
Citation for websites and book-like ressources

### ISSUE THREAD

**Issue by ShadowMitia** [citation-file-format/citation-file-format#358]
Hello!

I'm having an issue about the citation file, I'm not sure what category it qualifies as exactly, sorry...

I'm a (new) contributor over at [the Arcane Algorithm Archive](github.com/algorithm-archivists/algorithm-archive/) and there were talks there of using this file for citing the project.

### What is the current guideline/suggestion for citing a website resource as a direct citation?

Please see the following link for the issue I'm working on for more context : https://github.com/algorithm-archivists/algorithm-archive/pull/891

To summarise the website: it describes algorithms with example codes in several languages. Some of these algorithms have or will have papers associated with some of the authors of the website, and the whole project is based on open research principles.

Another example of a website that could be cited (and has a citation suggestion on the website already!) is https://github.com/RayTracing/raytracing.github.io. It does qualify as a book ressource as well, but currently also doesn't qualify for the citation format as it currently holds.

### Is the citation format designed only around software and data?

I might've misunderstood the scope of the file format, but it is surprising to me that most of the types in the `reference` level aren't usable at the top level of the format as well.

Any kind of feedback would be greatly appreciated, thanks!

**Comment by sdruskat** [comment]
Hi @ShadowMitia, and thanks for opening this issue!

To answer your last question: Yes, the format is designed to only hold citation metadata for software (and experimentally also for datasets). There may be a discussion to be had about whether a website counts as software, but that's not for me to decide in your case. Anyhow, because the `references` section is to hold references to things that the software cites (or builds on like a paper builds on other papers, e.g., dependencies, definitions of algorithms it implements, etc.), this is the only place where we have BibTeX-like types.

I hope this helps. I'll close this, but please let me know if there are further questions.

**Comment by ShadowMitia** [comment]
It clears up a few things, thanks!

**Comment by ShadowMitia** [comment]
Could the `preferred-citation` be used as a workaround for this? Would it make sense?

I've come up with this based on the citation info of [Raytracing in One Week End](https://raytracing.github.io/books/RayTracingInOneWeekend.html#citingthisbook)

```
cff-version: 1.2.0
message: "If you use this book, please cite it as below."
authors:
  - family-names: Shirley
    given-names: Peter
    orcid: https://orcid.org/0000-0003-1254-8770
preferred-citation:
  authors:
    - family-names: Shirley
      given-names: Peter
      orcid: https://orcid.org/0000-0003-1254-8770
  title: "Ray Tracing in One Weekend"
  type: website
  url: https://raytracing.github.io/books/RayTracingInOneWeekend.html
  repository-code: https://github.com/RayTracing/raytracing.github.io
  editors:
    - family-names: Hollasch
        given-names: Steve
    - family-names: Black
        given-names: Trevor David  
  version: 3.2.3
  copyright: "CC0 1.0 Universal"
  release-date: 2020-12-07
  abbreviation: RTW1
references:
  - collection-title: "Ray Tracing in One Weekend Series"
    type: website
    url: https://raytracing.github.io/
    repository-code: https://github.com/RayTracing/raytracing.github.io
```

Or should this be a `reference`?
