### ISSUE TITLE
Should the schema protect against trailing spaces in author names?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#380]
Spawned from https://github.com/citation-file-format/cff-initializer-javascript/issues/221

**Comment by sdruskat** [comment]
For context, is this about "cleaning up" user input from cffinit that may contain trailing spaces?

If so, I'm not sure but also don't have any strong opinion about whether this should be solved in the schema. Some points:

- Given that a string contains trailing spaces, I'd assume that downstream clients/applications would be able to fix this just as well, and are perhaps in a better place to do so. 
- In fact, I think there's a good case to be made for cffinit cleaning up trailing spaces itself, as it is responsible for writing valid (and arguably also well-formed) CFF. From a user perspective, I wouldn't be surprised if such an app did this. But perhaps I don't understand any deeper issues in cffinit with this?
- If we decide to fix this, this would be a breaking change I think, so would schedule this for v2.
- Does it make sense to apply this to all strings? Do we want to guess if there are valid user inputs that should contain trailing spaces?

**Comment by jspaaks** [comment]
> Given that a string contains trailing spaces, I'd assume that downstream clients/applications would be able to fix this just as well, and are perhaps in a better place to do so.

For sure this is possible, but difficult to do in a consistent manner across various tools. For example, I may use cffinit to write 

![image](https://user-images.githubusercontent.com/4558105/174641932-ec023085-f0c7-4e79-b6cb-2c3558b7511b.png)

Without realizing that there is a trailing space, even though it is visible in the yaml

```yaml
cff-version: 1.2.0
title: Mytitle
message: Mymessage
type: software
authors:
  - given-names: 'Jurriaan H. '
    family-names: Spaaks
```
Even if I do notice it, it's not invalid according to the schema, so I'd say it's well formed and anyway, it's what cffinit gave me so I'm not gonna correct it as a user. But then, it's conceivable that another tool like cffconvert or ruby-cff could make different choices and assume the space is never there, potentially leading to minor errors for example when building the author's name from its constituent parts using concatenation.

Additionally, one could argue that it's odd to have a set of rules mandated by the schema, but then an additional set of rules local to a tool, which would be necessary for detecting duplicates via the schema's `uniqueItems: true`, for example when you have:

![image](https://user-images.githubusercontent.com/4558105/174645909-935c2735-5d01-4953-9d1d-f4722f46ce5f.png)

cffinit correctly (but counterintuitively) doesnt trigger a "duplicate item" warning because:
```
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: Mytitle
message: Mymessage
type: software
authors:
  - given-names: 'Jurriaan H. '
    family-names: Spaaks
  - given-names: Jurriaan H.
    family-names: Spaaks
```
