### ISSUE TITLE
Version from file

### ISSUE THREAD

**Issue by z-a-f** [citation-file-format/citation-file-format#383]
Getting a version number from a separate file could improve the usability.

**Use case**

In large repositories like [PyTorch](https://github.com/pytorch/pytorch), the versioning information is stored in a separate location. This is done for backwards compatibility, as well as simplified version update in a rapidly evolving project.

## Proposal 1. Add a `version-file` entry

In addition to the `definitions.version`, there could be a `definitions.version-file`:

```markdown
### `version-file`

- **type**: [`definitions.reference.filename`](#definitionsreferencefilename)
- **required**: `false`
- **description**: File path containing the version of the software or dataset.
- **usage**:<br><br>
    ```yaml
    version-file: VERSION
    ```
    ```yaml
    version-file: version.txt
    ```
```

One issue with this proposal is conflict resolution in case of colliding `version` and `version-file` entries.

## Proposal 2. Change the definitions

### Proposal 2a. The parsers would need to check if the string in the `version` field is a file in the same location as the `CITATIONS.cff`.

```markdown
### `definitions.reference.version`

- **type**: [`definitions.version`](#definitionsversion)
- **required**: `false`
- **description**: The version of the work.
- **usage**:<br><br>
    ```yaml
    preferred-citation:
      type: generic
      version: 0.3.12
    ```
    ```yaml
    references:
      - type: generic
        version: 0.3.12
    ```
    ```yaml
    preferred-citation:
      type: generic
      version: version.txt
    ```

### `definitions.version`

- **type**: [Nonempty `string`](#yaml-strings), `number`, or [`filename`](#definitionsreferencefilename)
- **required**: N/A
- **description**: The version of a work.
- **usage**:<br><br>
    ```yaml
    version: "1.2.0"
    ```
    ```yaml
    version: 1.2
    ```
    ```yaml
    version: "21.10 (Impish Indri)"
    ```
    ```yaml
    version: VERSION
    ```
    ```yaml
    version: version.txt
    ```
```

Not sure if that's even possible, given that the `filename` is a string as well.

### Proposal 2b. Amend the definition of the `filename`

If the filename follows the format of the [`license-url`](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#license-url) and specifically the [`definitions.url`](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsurl), it would be possible to let the parsers identify the files. It might be worth creating an explicit `filename` definition.

Here is an example

```markdown
### `definitions.filename`

- **type**: [Nonempty `string`](#yaml-strings)
- **required**: N/A
- **description**: The name of the electronic file containing the work. Supported file paths should either be a string, or in case of ambiguous usecase, should start with one of:
    - `file://`
    - `/`
- **usage**:<br><br>
    ```yaml
    preferred-citation:
      filename: CITATION.cff
      type: generic
    ```
    ```yaml
    references:
      - filename: CITATION.cff
        type: generic
    ```
    ```yaml
    preferred-citation:
      filename: file://citations/CITATION.cff
      type: generic
    ```
    ```yaml
    references:
      - filename: /citations/CITATION.cff
        type: generic
    ```

### `definitions.version`

- **type**: [Nonempty `string`](#yaml-strings), `number`, or [`filename`](#definitionsfilename)
- **required**: N/A
- **description**: The version of a work.
- **usage**:<br><br>
    ```yaml
    version: "1.2.0"
    ```
    ```yaml
    version: 1.2
    ```
    ```yaml
    version: "21.10 (Impish Indri)"
    ```
    ```yaml
    version: "file://VERSION"
    ```
    ```yaml
    version: "/version.txt"
    ```
```
```
