### ISSUE TITLE
Why do ORCiDs require specifying resolver IDs, while DOIs do not?

### ISSUE THREAD

**Issue by aweinert** [citation-file-format/citation-file-format#388]
When giving an ORCiD for an author, the schema requires me to give the resolver URL, i.e., to write `orcid: "https://orcid.org/0000-0001-8143-246X"` instead of `orcid: "0000-0001-8143-246X"`. In contrast, when specifying DOIs, the schema requires me to write
```
identifiers:
  - description: "The concept DOI of the software."
    type: doi
    value: 10.5281/zenodo.3691674
```
instead of
```
identifiers:
  - description: "The concept DOI of the software."
    type: doi
    value: "https://doi.org/10.5281/zenodo.3691674"
```
What is the conceptual difference between the two kinds of identifiers that I am not seeing here?
