### ISSUE TITLE
CITATION.cff file cannot be parsed

### ISSUE THREAD

**Issue by duythanhvn** [citation-file-format/citation-file-format#390]
Please note that issues with the validity of single CITATION.cff files may take some time to be picked up by the Citation File Format maintainers themselves. Therefore, if you are reading this issue and know how to validate `CITATION.cff` files, please help out if you can!

## Invalid `CITATION.cff` file

```yaml
cff-version: 1.2.0
message: 'We appreciate, but do not require, attribution.'
references:
  type: book
  author:
  - family-names: 'Doan'
    given-names: 'Thanh'
  title: 'Book Name'
  year: 2022
  edition: '2nd'
  publisher: 
  - name: O"Reilly Media, Inc.
  - website: https://www.oreilly.com/
  isbn: 9781113333222
url: 'https://github.com/'
```

## Context
Please describe what you want to do 
- create a valid `CITATION.cff` file
- show the citation information in the sidebar of your GitHub repository

**Comment by jspaaks** [comment]
Hi @duythanhvn and welcome!

There's a couple of things I can see, I'll walk you through them:

- There are a few required properties missing in the root of the document: `authors` and `title`
- `references` should be an array, so I added the `-` and indented the reference
- `references.author` should be plural even if there's just one author
- `references.publisher` is an object, so no need for the dashes there 
- ISBN without any quotes is interpreted as a number, but it expects a string. You can either quote it or insert dashes to make YAML parsers interpret its value as a string.

Finally, note that `url` currently describes whatever software you choose to put in the root document. `references` also have the `url` property, but it would need to be indented if you want it part of the reference.

Making those changes, I ended up with 

```yaml
cff-version: 1.2.0
authors:
  - family-names: 'Doan'
    given-names: 'Thanh'
message: 'We appreciate, but do not require, attribution.'
title: 'The title of the software'
references:
  - type: book
    authors:
    - family-names: 'Doan'
      given-names: 'Thanh'
    title: 'Book Name'
    year: 2022
    edition: '2nd'
    publisher:
      name: O'Reilly Media, Inc.
      website: https://www.oreilly.com/
    isbn: '9781113333222'
url: 'https://github.com/'
```

If I save that snippet as `CITATION.cff` and run `cffconvert --validate` in its directory (`cffconvert` is available from PyPI https://pypi.org/project/cffconvert/), I get 

```shell
Citation metadata are valid according to schema version 1.2.0.
```

You can read more about the format in the Guide to the Schema: https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md
