### ISSUE TITLE
Add type for specifications / standards

### ISSUE THREAD

**Issue by m-mohr** [citation-file-format/citation-file-format#403]
In my domain a lot of (technical) specifications / standards are written and authored on GitHub, e.g. from the OGC (Open Geospatial Consortium, an international standards body at https://github.com/opengeospatial).
The `type` field only allows for software and dataset. 
I'd like to propose to also allow specifications (i.e. techreport in BiBTeX).

Here's an example for the STAC specification:

```yaml
cff-version: 1.2.0
message: "If you are referring to the STAC specification in your publications, please cite it as below."
type: specification
title: "SpatioTemporal Asset Catalog (STAC) specification"
abstract: "Making geospatial assets openly searchable and crawlable."
version: 1.0.0
date-released: 2021-05-21
license: Apache-2.0
url: https://stacspec.org
repository: "https://github.com/radiantearth/stac-spec"
authors:
  - name: "STAC Project Steering Committee"
contact:
  - email: "stac-psc@radiant.earth"
    name: "STAC Project Steering Committee"
```
