### ISSUE TITLE
`person` name fields sometimes misinterpreted

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#421]
During the analysis of some CFF files I've come across files that misinterpret the field names of `person`object, specifically - I think - becuase of their their plural form (`given-name*s*`, `family-name*s*`).

E.g., for three separate authors *Stephan Druskat*, _Jurriaan H. Spaaks_, _Foo Bar_, you'd see something like

```yaml
authors:
  - family-names: Druskat, Spaaks, Bar
  - given-names: Stephan, Jurriaan H., Foo
```

While usage is documented clearly in the docs, I wonder if there is something that we can do to help people use the fields correctly.
