### ISSUE TITLE
Reference documentation of the software

### ISSUE THREAD

**Issue by B3J4y** [citation-file-format/citation-file-format#455]
There's no way to reference the generated documentation of your work in the CFF.

Included options are:

* Identifiers: however, documentation isn't an identifier.
* URL: This is designed for landing pages, which could link to the documentation, but this isn't directly visible in the CFF.
* References: It's quite challenging to use this to reference your documentation.

I suggest allowing the 'URL' field to accept an array. This array of URLs (comprising type and URL) could link to the landing page, documentation, institute page, etc. By further defining potential categories, the list could expand over time. What do you think about this suggestion?

**Comment by kevinmatthes** [comment]
@B3J4y

Great idea!

If I understand your suggestion correctly, the solution would look like this, at the end:

```yml
- url:
  - description: This is the documentation.
    value: # URL 1
  - description: This is the project page.
    value: # URL 2
```

In addition, as citing a project's documentation also seems to me to be a very common use case, adding a dedicated `repository-documentation` field might be another option to take into account for discussion.

Furthermore, I would like to add some information on my experiences with the CFF URL field and self-citing a project.

- The Rust projects I encountered so far usually state the URL of the generated documentation as linked website in the GitHub project description (link to docs.rs).  If these projects furthermore have a CITATION.cff configured, they usually enter their docs.rs URL in the CFF `url` field.  However, this procedure might be specific to Rust projects somehow.
- To (self-)cite a project, I developed a CLI named Aeruginous (https://crates.io/crates/aeruginous) which is capable of processing a given input CFF to turn the relevant data into a CFF reference object.  This reference object can then be added to the respective CITATION.cff's list of references.  It is also possible to append one project's CFF data to its own list of references; `aeruginous cffreference -i CITATION.cff -o CITATION.cff`.  The tool also accepts remote CFFs collected with curl:  `curl https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/CITATION.cff | aeruginous cffreference -o CITATION.cff`.  This can be used to create a basic entry to add one's documentation URL.

**Comment by B3J4y** [comment]
Cool stuff! Thank you for your comment. I was looking for a tool to generate a reference for CFF from a CFF. Aeruginous is the answer.

I'd expand on your example a bit::
```
- url:
  - description: This is the documentation.
    type: documentation
    value: # URL 1
  - description: This is the project landingpage.
    type: landing
    value: # URL 2
  - description: This is the project api endpoint.
    type: api
    value: # URL 3
```

A 'type' would be useful for automatically converting this into the required formats.

I plan to use this to create a GitHub/GitLab page with https://github.com/University-of-Potsdam-MM/cff2pages.

**Comment by kevinmatthes** [comment]
- For the `type` field, maybe there is a list of common types already available somewhere such that it could be taken into account for implementation.  I agree that limiting the type to certain values is a useful feature for automation / processing.
- Regarding Aeruginous, I am working on a GitHub Action, at the moment, to auto-fetch known project CFFs when a certain condition is met.  E.g., whenever your project's manifest is updated because any update bot submitted an update to a dependency, Aeruginous will `curl` the raw CFF of that dependency project to update your CFF's list of references.  If you are interested in such a feature, as well, please let me know such that I can take your feedback into account for the further development.
- Finally, the README of *this* repository contains a table of available CFF-related tools.  If you would like to, you can raise an issue to request adding your tool to the collection such that other users searching for exactly that functionality can find your software more easily.  Please note that the integration of any new software to the table might take some time; as the request(s) for Aeruginous (and some other software I wrote) is (are) still pending, you cannot find the tool(s) directly using the tooling catalogue.

**Comment by jspaaks** [comment]
Hi folks,

I think I would still use `identifiers`, because that can take a URL as well:

https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsidentifier

so you would for example do:

```yaml
cff-version: 1.2.0
message: The message
title: The title
authors:
  - name: The Team
identifiers:
  - description: This is the documentation.
    type: url
    value: https://where.the/documentation/lives
  - description: This is the project landingpage.
    type: url
    value: https://where.the/landingpage/lives
  - description: This is the project api endpoint.
    type: url
    value: https://where.the/api/lives
```

Additionally, it looks like the next release will have relation type qualifiers like DataCite/Zenodo, so you can annotate each identifier with strings like `documents`, `isCompiledBy`, `isSourceOf` etc.
