### ISSUE TITLE
[question] How to deal with multiple affiliations?

### ISSUE THREAD

**Issue by aaronpeikert** [citation-file-format/citation-file-format#457]
Often authors are affiliated with more than one institution. How would this be reflected in a CFF file?

We tried this:

```
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: >-
  Introduction to Julia | A fresh approach to scientific
  computing
message: Please cite this material if you happen to find it useful.
type: software
authors:
  - given-names: Aaron
    family-names: Peikert
    email: peikert@mpib-berlin.mpg.de
    affiliation: Max Planck Institute for Human Development
    orcid: 'https://orcid.org/0000-0001-7813-818X'
  - family-names: Ernst
    given-names: Maximilian Stefan
    email: ernst@mpib-berlin.mpg.de
    affiliation:
      - Max Planck Institute for Human Development
      - Max Planck School of Cognition
    orcid: 'https://orcid.org/0000-0003-2237-6255'
  - family-names: Ketzer
    given-names: Moritz
    email: moritz.ketzer@hu-berlin.de
    affiliation:
      - Max Planck Institute for Human Development
      - Humboldt-Universität zu Berlin
    orcid: 'https://orcid.org/0000-0002-2403-5297'
identifiers:
  - type: doi
    value: 10.5281/zenodo.8059528
repository-code: 'https://github.com/formal-methods-mpi/Workshop.jl/'
license: CC0-1.0
```

But affiliation seems only to take a single string:

https://github.com/formal-methods-mpi/Workshop.jl/actions/runs/6156316183

https://github.com/formal-methods-mpi/Workshop.jl/pull/82#issuecomment-1714536876
