### ISSUE TITLE
Should `authors` be unique items?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#472]
When testing PR #462, I stumbled over the fact that `authors` can only contain unique items as per https://github.com/citation-file-format/citation-file-format/blob/main/schema.json#L1111.

I'd like to discuss whether we should remove this requirement for 1.3.0.

My current thinking is that we should remove the requirement, as this allows the representation of factual author lists.

### Reasons for making `authors` not unique

- \> 1 authors may share a name, e.g., in the case of common names, and especially preference of abbreviated given names, where _Jane Doe_ and _John Doe_ would both be _J Doe_. This cannot be recorded in a CFF file:

```yml
...
# The below is illegal
authors:
  - family-names: Doe
    given-names: J
  - family-names: Doe
    given-names: J
```

### Reasons for keeping `authors` unique

- When creating and updating files manually, or through copy and paste, it may happen that author entries are inadvertently being duplicated. This, however, is a tiny fraction of problems that may occur from handling metadata wrongly.
- The above invalid example for removing the requirement can be resolved by adding a third datapoint to _at least_ one of the duplicates, e.g., `orcid` or `email`. I.e., the following examples are valid. However, the first one actually feels like a duplicate to me as a human reader, although formally they're unique.

```yml
authors:
  - given-names: J
    family-names: Doe
  - given-names: J
    family-names: Doe
    orcid: https://orcid.org/1234-4321-1234-4313
```

```yml
  - given-names: J
    family-names: Doe
    email: j.doe@email.tld
  - given-names: J
    family-names: Doe
    orcid: https://orcid.org/1234-4321-1234-4313
```

**Comment by sdruskat** [comment]
@jspaaks On a meta note, I'd like to add this to the 1.3.0 milestone to resolve. Would you agree?

**Comment by jspaaks** [comment]
I'd be OK with making `authors` non-unique. Duplicate authors are an issue, but `uniqueItems: true` does not guarantee anything, e.g.

```yaml
cff-version: 1.2.0
authors:
 # 3 authors where there should be 1
 - given-names: Jurriaan
 - given-names: Jurriaan H.
 - given-names: Jurriaan
   family-names: Spaaks
message: The message
title: The title
```
