### ISSUE TITLE
Elaborate / example on grant specification

### ISSUE THREAD

**Issue by yarikoptic** [citation-file-format/citation-file-format#491]
in particular for the use with zenodo.

ATM it is not clear to me how to reference funding. We would like to use CITATION.cff in place of `.zenodo.json`. In our [.zenodo.json](https://github.com/datalad/datalad/blob/maint/.zenodo.json) we have

```json
    "grants": [
        {
            "id": "10.13039/100000001::1429999"
        }
    ]
```
to point to NSF grant ... and that ID is a DOI for NSF apparently: http://dx.doi.org/10.13039/100000001 which redirects to http://data.crossref.org/fundingdata/funder/10.13039/100000001  (I didn't know).

But I am not sure what to enter in CITATION.cff which we have without "grants" for now: https://github.com/datalad/datalad/blob/maint/CITATION.cff

attn @TheChymera

**Comment by Moritz-Alexander-Kern** [comment]
Would also be interested in this, currently we are using a `.zenodo.json` with a "grants" field.

```json
    "grants": [
        {"id": "604102"},
        {"id": "720270"},
        {"id": "785907"},
        {"id": "945539"}
    ],
```


See: https://github.com/NeuralEnsemble/elephant/blob/master/.zenodo.json

**Comment by yarikoptic** [comment]
ping @jspaaks @sdruskat - would be great to work out the scheme for grants specification.

Given that zenodo now supports imports from CITATION.cff , attn @lnielsen of zenodo fame to possibly coordinate a solution.

**Comment by d33bs** [comment]
Just a bump to mention interest in a solution to this issue within the context of this file format! Without this addition it's likely people will adopt other formats or a funding-specific file within their projects.

**Comment by d33bs** [comment]
Could I propose a way to include funding information for the `CITATION.cff` format through this issue and repository? I don't know what needs to go into this in terms of the governing body of the project but figured I'd ask. As a default without reply I may open a PR to try and propose how this could work with the understanding that it might change significantly or need to be closed without a merge.

**Comment by yarikoptic** [comment]
Thank you @d33bs for taking the stub!  I think it might be worth aligning to how datacite does it : https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/fundingreference/

**Comment by d33bs** [comment]
Thanks @yarikoptic - the datacite reference is great! I'll use this as a basis to build an implementation.

**Comment by sdruskat** [comment]
Hello @d33bs, @yarikoptic et al., and thanks for your interest in adding grant information to CFF.

I think the important things to clarify for a potential PR to be considered for the schema are:

- How does funding information align with the scope of CFF (i.e., citation metadata for software)?
- Are there/what are grant identification standards that need to be considered?
- What is a minimum viable implementation? For example, would an award URI be enough to uniquely identify a grant, and what would be absolutely necessary for a grant that doesn't have a unique URI?

As you can tell from the sporadic active engagement with issues at the moment, we're a bit short on time to dedicate to the project just now, so maintenance of new additions is a real concern.

**Comment by d33bs** [comment]
Thanks @sdruskat ! Responding to your questions:

> How does funding information align with the scope of CFF (i.e., citation metadata for software)?

Adding software funding information helps properly credit foundations for creating or maintaining software (e.g. a grant which funds the building of the software). It would help increase the credibility of the software more generally by transparently enabling people to know how the software was created. This also aligns with open science principles and perhaps eventually requirements; some funders require that funding acknowledgements are provided upfront for software or work that relates to those funds.

> Are there/what are grant identification standards that need to be considered?

I don't know as much about grant identification standards. Anecdotally it seems somewhat distinct per funding organization but it might be good to understand what standards there are in the space.

> What is a minimum viable implementation? For example, would an award URI be enough to uniquely identify a grant, and what would be absolutely necessary for a grant that doesn't have a unique URI?

I feel an MVI would be close to what @yarikoptic shared from DataCite, also allowing for flexibility from the `.zenodo.json` format as well. All of this of course would be open to input from others here or in PR's, etc. For example:

```yaml
funding:
  - name: European Commission
    identifiers:
      type: Crossref Funder ID
      value: https://doi.org/10.13039/501100000780
    awards:
      - value: 282625
        url: https://cordis.europa.eu/project/rcn/100180_en.html
        name: MOTivational strength of ecosystem services and alternative ways to express the value of BIOdiversity
```

Maybe this needs to be more atomic, similar to the `references` fields?

> As you can tell from the sporadic active engagement with issues at the moment, we're a bit short on time to dedicate to the project just now, so maintenance of new additions is a real concern.

Thanks for the heads up. Would there be a better time in the near future to entertain new additions? Or are you meaning that the project has stalled and is in danger of being unsupported moving forward? My hope would be that we could continue improving it if possible :) .

**Comment by sdruskat** [comment]
Thanks, @d33bs, for answering these questions.

> Adding software funding information helps properly credit foundations for creating or maintaining software (e.g. a grant which funds the building of the software). It would help increase the credibility of the software more generally by transparently enabling people to know how the software was created. This also aligns with open science principles and perhaps eventually requirements; some funders require that funding acknowledgements are provided upfront for software or work that relates to those funds.

I agree. Additionally I'd say that funding information helps relate software to other research activities and outputs connected through grants, and thus can potentially help enrich the citation graph.
 
> I don't know as much about grant identification standards. Anecdotally it seems somewhat distinct per funding organization but it might be good to understand what standards there are in the space.

I was also thinking about this in terms of what is currently supported in other systems, and data types. In my - similarly anecdotally - experience with acknowledging funding (mostly in papers), a grant number (`string`), and less frequently a URI (`uri`) is used to do this.

In our experience, it is useful to support in CFF what is already used elsewhere. For publishing citable software, Zenodo has become the go-to place. The Zenodo metadata schema for depositions has a field `grants`:

![Image](https://github.com/user-attachments/assets/fd1ebcad-c95b-449d-9901-154d3cc40b34)
 
> I feel an MVI would be close to what [@yarikoptic](https://github.com/yarikoptic) shared from DataCite, also allowing for flexibility from the `.zenodo.json` format as well. All of this of course would be open to input from others here or in PR's, etc. For example:
> 
> funding:
>   - name: European Commission
>     identifiers:
>       type: Crossref Funder ID
>       value: https://doi.org/10.13039/501100000780
>     awards:
>       - value: 282625
>         url: https://cordis.europa.eu/project/rcn/100180_en.html
>         name: MOTivational strength of ecosystem services and alternative ways to express the value of BIOdiversity
> 
> Maybe this needs to be more atomic, similar to the `references` fields?

Hm, My gut feeling is that this would be too complex, and also duplicating information. Given the data we want to represent, I can see two pieces of information here: funder and grant. To make it as simple and straightforward as possible for users of CFF to provide this information, I'd suggest to allow for the most simple and an approximation of an "optimal" solution. Perhaps something like:

```yaml
funding:
    - funder: <str>/<uri> (optional)
      grant: <str>/<uri> (required)
```

This way, all the information can be provided in two ways:

```yaml
funding:
    # String-based, encoded in only the required field     
    - grant: "DFG grant 1234567"

    # Lossy, but possible
    - grant: "1234567"

    # String-based, using both fields
    - funder: "DFG" 
      grant: "1234567"

    # URI-based, encoded in only the required field
    - grant: "https://doi.org/10.1234/dfg::1234567"

    # URI+string-based
    - funder: "https://doi.org/10.1234/dfg"  
      grant: "1234567"

    # Fully URI-based, if duplicating information
    - funder: "https://doi.org/10.1234/dfg"  
      grant: "https://doi.org/10.1234/dfg::1234567"
```
 
> Thanks for the heads up. Would there be a better time in the near future to entertain new additions? Or are you meaning that the project has stalled and is in danger of being unsupported moving forward? My hope would be that we could continue improving it if possible :) .

No, the project continues, it is (currently) unfunded but not unsupported, meaning that things take a little more time at the moment 🙂. Now is as good a time as any to put forward a PR, but it may take time before it sees action.
