### ISSUE TITLE
How should CFF store different parts of someone's name?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#513]
(spawned from #329, ping @AdityaSavara @acli @r12a @jodischneider @kevinmatthes )

How should we store different parts of someone's name in CFF in order to

1. support accuracy in converting to other formats
1. support abbreviation of certain parts of someone's name
1. support sorting of someone's name in a list of names, e.g. a list of references in a journal paper
1. support reordering parts of someone's name

I'm not hopeful we'll be able to come up with "the ideal solution" quickly, but at least this issue should serve as a place where we can discuss the relevant aspects.

**Comment by kevinmatthes** [comment]
In my opinion, we are quite likely to need additional fields for the `person` type.  A good starting point might be to define an optional field `name-properties` where we could define the relevant additional information as further sub-fields.  For instance, regarding the name part reordering, CFF supports four types of name parts as of this writing:

- `family-names`
- `given-names`
- `name-particle`
- `name-suffix`

A field `name-properties.ordering` could now support either a sorted list of the name parts or some short-hand:

```yml
authors:
  - family-names: Xample
    given-names: Emma
    name-particle: de
    name-suffix: XLII

    name-properties:
      # Option 1.
      - ordering: GPFS # Given name(s), name Particle(s), Family name(s), and name Suffix(es).

      # Option 2.
      - ordering:
        - given-names   # 1.
        - name-particle # 2.
        - family-names  # 3.
        - name-suffix   # 4.
```

The shown example uses an abbreviation-based short-hand originating from the most relevant letters in the four available name part fields.  As there are only $4! = 24$ possibilities to sort the names, the short-hands could be also hard-coded into the schema allowing for more accurate validation.  If some name part should be listed in the `ordering` but not defined in the `person` entity, the respective name part should be just skipped during assembly without causing an error.

The short-hand approach for ordering also allows for implementing the abbreviation preferences quite easily by associating the abbreviation criterion with the respective short-hand letter's case, e.g. with the above name, `ordering: gpFs` could result in `E. Xample` (i.e. abbreviating the `given-names` as well as skipping both `name-particle` and `name-suffix`).  In case that some given name, family name, name particle, and / or name suffix should not be abbreviated, another field `name-properties.primary-name` could store this information as a list of strings.  If one of these strings matches one of the words in the given name parts, this word should not be abbreviated.

And, finally, with respect to the sorting within a list of names, there might be another field `name-properties.list-entry` which accepts an integer to determine the appearance of that particular name within the compiled list of names.  If the `list-entry` numbers should not be subsequently, e.g. $\\{ 100, 42, 256, 3 \\}$, it is still possible to sort the `person` entities by the `list-entry` numbers as they still can be compared against each other due to the total ordering relation on integer numbers.  In case of duplicate numbers, the compiled name strings, i.e. after applying the name part ordering and abbreviation settings, could be compared against each other by the ASCII / Unicode values of the resulting characters / grapheme clusters as a secondary ordering criterion.

For exporting the data to other formats, a conversion of the name to a string according to the `name-properties` would be the simplest fall-back solution if there should not be any matching fields.
