### ISSUE TITLE
Add support for `resourceType` from DataCite in Zenodo

### ISSUE THREAD

**Issue by alexlancaster** [citation-file-format/citation-file-format#531]
Hi there, now that there is support for the DataCite "relation" in CFF 1.3.0 via #459 , I wonder if there are plans to also support the `resourceType` and/or `resourceTypeGeneral` from DataCite?

https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/resourcetype/

Then it could be paired with a `relation` within an `identifer`, like so:

```yaml
identifiers:
 - description: Software package
    type: doi
    value: https://pypi.org/project/pypop-genomics/
    relation: IsSupplementTo
    resource: Software
```

The Zenodo backend uses this field for all identifiers, so the above would be transformed into a `.zenodo.json` like:

```json
   "related_identifiers": [
        {
            "scheme": "doi",
            "identifier": "https://pypi.org/project/pypop-genomics/",
            "relation": "isSupplementTo",
            "resource_type": "software"
        },
```
On the Zenodo cite, this `resource_type` is used in the UI to indicate the nature of the resource pointed to.
