### ISSUE TITLE
Introduce `parent-doi`

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#69]
A field `parent-doi` (or similarly named) shall be introduced to record *project level* DOIs, such as those in Zenodo, which collect child DOIs, i.e., version DOIs.

This will ensure sustained access to a software via the parent DOI, for which a landing page may exist which points to all versions, or the latest version.

This field shall be non-required.

**Comment by sdruskat** [comment]
@jspaaks Should this become part of 1.1.0 as well? It's cheap and useful to have (e.g., the RSD works on parent DOIs, right?).

I don't want to introduce unnecessary complexities (introducing this as part of 1.1.0 is feature-creepy enough), therefore I'd suggest to actually introduce `parent-doi`for the particular DOI use case. (This would also be in line with the principles, which suggest to use DOIs above other identifiers.)

If other identifiers exist that know the parent-version relationship, this could always be implemented as two complex types of identifier (cf. https://github.com/citation-file-format/citation-file-format/issues/85#issuecomment-551016103), i.e.:

```yaml
identifiers:
  - type: custom-id
    value: cid://imacustomid
  - type: custom-id-parent
    value: cid://imabovecustomid'sparent
```
