### ISSUE TITLE
Regular expression for DOIs too narrow

### ISSUE THREAD

**Issue by thomaskrause** [citation-file-format/citation-file-format#92]
I use the DOI `10.1093/llc/fqu057`in one of my citation files. The validator complaints that the DOI does not match a regular expression and is invalid. This is not true, the DOI can be resolved without issues:  http://doi.org/10.1093/llc/fqu057

Validating with cffconvert gives the following error message:
```
 --- All found errors ---
validation.invalid
 --- All found errors ---
["Value '10.1093/llc/fqu057' does not match pattern '^10\\.\\d{4,9}(\\.\\d+)?/[A-Za-z0-9-\\._;\\(\\)\\[\\]\\\\\\\\:]+$'. Path: '/references/0/doi'", "Value '1' is not of type 'str'. Path: '/references/0/issue'"]
```
CFF version is 1.0.3.

Test file (with fewer authors than in the actual file)
```
# YAML 1.2
# Metadata for citation of this software according to the CFF format (https://citation-file-format.github.io/)
cff-version: 1.0.3
message: If you use this software, please cite it using these metadata.
title: 'ANNIS'
doi: 10.5281/zenodo.2563138
authors:
- given-names: Thomas
  family-names: Krause
  affiliation: Humboldt-Universität zu Berlin
  orcid: https://orcid.org/0000-0003-3731-2422
version: annis-3.6.0
date-released: 2019-02-12
repository-code: https://github.com/korpling/ANNIS
license:  Apache-2.0
references:
  - type: article
    title: "ANNIS3: A new architecture for generic corpus query and visualization"
    year: 2016
    doi: 10.1093/llc/fqu057
    authors:
      - family-names: Krause
        given-names: Thomas
        orcid: https://orcid.org/0000-0003-3731-2422
        affiliation: Humboldt-Universität zu Berlin
      - family-names: Zeldes
        given-names: Amir
        affiliation: Georgetown University
    journal: Digital Scholarship in the Humanities
    volume: 31
    issue: 1
    issn: 2055-7671
```
