### ISSUE TITLE
Add section on validation to README

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#94]
The README from https://github.com/citation-file-format/schema needs to be incorporated 

- in the README, 
- or in the landing page at .github.io,
- or in a separate README-like file for working with the schema, e.g., VALIDATION.md. 

It includes important information on installing pykwalifire, including missing information on having to have python3-dev installed, otherwise `pip install pykwalifire` won't work...

@jspaaks My initial feeling is that this should go in a separate file in this repo (SCHEMA.md or VALIDATION.md). Any preferences?

**Comment by sdruskat** [comment]
Also mention that `pytest` should be installed, as well as `cffconvert`.

**Comment by sdruskat** [comment]
And that installing `cffconvert` needs `pip install wheel`.

**Comment by sdruskat** [comment]
After having commented on #85 (https://github.com/citation-file-format/citation-file-format/issues/85#issuecomment-552432806), I think that the schema should be documented in a file `SCHEMA.md`, which contains:

- What the schema is
- How it can be used to validate `CITATION.cff` files
- How it can be changed, e.g., how to introduce new identifier types

**Comment by jspaaks** [comment]
I think that would potentially mix two target audiences wouldn't it? I think people who are writing a CFF file, i.e. "users" would want a "Guide to understanding the schema" (your first bullet I think). I'm in favor of having that in a separate file and would call that ``guide-to-understanding-the-schema.md`` or possibly ``schema.md`` (no caps) if you're a fan of brevity. another benefit would be that ``schema.yaml`` and ``schema.md`` would be adjacent in file listings. 

Another type of person, i.e. "developers" (and probably also "maintainers"), would need information on how to make changes to the schema. I'd say that should not be part of ``schema.md``, but maybe in ``CONTRIBUTING.md``? (that file would then also need to cover validation)

Regarding validation of CFF files by users, maybe we should delegate that to e.g. tooling repos like cffconvert?

**Comment by sdruskat** [comment]
+1 having `schema.md` for bullet 1, putting the rest in `CONTRIBUTING.md` (also change the link to that in the README section about identifier types & how to add new ones), and for delegating the validation to tooling.

**Comment by jspaaks** [comment]
BTW I'd be open to moving CONTRIBUTING.md to the root level.

**Comment by sdruskat** [comment]
> BTW I'd be open to moving CONTRIBUTING.md to the root level.

Go! Only place it makes sense in this setup.

**Comment by sdruskat** [comment]
Decision: Add validation section to CONTRIBUTING.md

**Comment by rpgoldman** [comment]
Delegating validation to tooling makes sense as a division of labor for development, but for *users* it would be really helpful to have a validation HOWTO on the front page in this repo, *especially* because this repo is what the GitHub docs page points to.  Even better would be for that pointer to be to a validation web application so that people could drop in their `CITATION.cff` files and get a quick check.

Right now, we are kind of assuming that anyone who is going to try to write a `CITATION.cff` file understands JSON/YAML schema validation, which seems like too big an ask.  People just want to put up a citation file, not master a new toolchain.

**Comment by sdruskat** [comment]
Hi @rpgoldman, and thanks for your comment!

The GitHub docs link to https://citation-file-format.github.io/ (maintained in https://github.com/citation-file-format/citation-file-format.github.io), and it will be updated for the release of schema version 1.2.0, which we're preparing now. It is valuable input to hear that there should be a validation section in the documentation there as well, and perhaps also here in the repository. We'll figure something out :).

**Comment by rpgoldman** [comment]
@sdruskat As an example of the user-level challenges, all I could figure out about how to validate my `CITATION.cff` file was to translate the CFF schema to json, translate `CITATION.cff` to JSON, and then use the python tool `jsonschema`.  Which errored out, and when I tested the CFF schema (translated to json) against the JSON schema meta schema, `jsonschema` rejected the CFF schema.  I haven't figured out how to get `jsonschema` to give me comprehensible output. It seems to just echo the schema to stderr and append the helpful phrase " is not
valid under any of the given schemas".  😜

So kind of a big pull for someone who just wanted to put a citation file on their GitHub repo!

**Comment by sdruskat** [comment]
Ouch indeed, and sorry for that, we'll work to make this much more easy to do. One part of this will be that we switch from YAML Schema to JSON Schema for 1.2.0. 

If you look at the script in the `1.2.0` branch (https://github.com/citation-file-format/citation-file-format/blob/1.2.0/examples/schema_poc.py) you can see how you can validate your CITATION.cff against the new schema (version as-is is [here](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema.json), but probably won't change before release). The 

script uses Python's *jsonschema* library as well. The only thing to keep in mind is that validators need to deserialize YAML timestamps (which are their own datatype) into strings :).

**Comment by sdruskat** [comment]
Some options for future reference:

- Wrap `schema_poc.py` into a docker container
- Provide as notebook via binder
- Use some https://jsonschemalint.com/ magic
- Write a tutorial for different languages (start with Python and *jsonschema*-based validation)

**Comment by rpgoldman** [comment]
@sdruskat I like the idea of putting `schema_poc.py` in a docker container.

I was able to use it in my local python environment, and fixed a couple of errors so that jsonschema was happy with my `CITATION.cff` file.  But ... maybe that's necessary but not sufficient?  My repo on this branch https://github.com/shop-planner/shop3/tree/add-citation has a `CITATION.cff` installed, and I see the "View Citation File" button but that button doesn't do anything when I press it (Firefox and Safari) and I don't see the "APA" and "Bibtex" options.

There is probably some more appropriate place to report this, but I don't know what that would be.

**Comment by sdruskat** [comment]
Looks like you're missing the `authors` field in the root of the file, i.e., with no indentation.

**Comment by rpgoldman** [comment]
Thanks. I *almost* have it fixed, but when I restore the `authors` and `title` to the top level, I get this error in the validation:

```
found duplicate key "title" with value "Hierarchical Task Network Planning in Common Lisp: the case of SHOP3" (original value: "SHOP3 HTN Planner")
  in "CITATION.cff", line 44, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
```

It seems like the schema is happy with me having authors for the software (top level) and authors for the paper (nested in the `conference-paper`).  But if I have a `title` at the top level and a `title` for the conference-paper, I get a validation error.

Here's the file that passes cleanly:
```
# YAML 1.2
---
authors: 
  -
    affiliation: "SIFT, LLC"
    family-names: Goldman
    given-names: Robert
    name-particle: "P."
    orcid: "https://orcid.org/0000-0002-5851-4851"
  -
    affiliation: "SIFT, LLC"
    family-names: Kuter
    given-names: Ugur
# title: "SHOP3 HTN Planner"
references:
  - type: conference-paper
    title: "Hierarchical Task Network Planning in Common Lisp: the case of SHOP3"
    collection-title: Proceedings of the 12th European Lisp Symposium
    editors:
        - family-names: Neuss
        - given-names: Nicolas
    year: 2019
    isbn: 978-2-9557474-3-8
    issn: 2677-3465
    conference:
      name: European Lisp Symposium
      location: Genova, Italy
      date-start: 2019-04-01
      date-end: 2019-04-02
    authors: 
      -
        affiliation: "SIFT, LLC"
        family-names: Goldman
        given-names: Robert
        name-particle: "P."
        orcid: "https://orcid.org/0000-0002-5851-4851"
      -
        affiliation: "SIFT, LLC"
        family-names: Kuter
        given-names: Ugur
cff-version: "1.2.0"
# date-released: 2019-04
message: "If you use this software, please cite it using this conference paper."
title: "Hierarchical Task Network Planning in Common Lisp: the case of SHOP3"
...
```

But if I uncomment the top level `title:` line, I get a validation error.  I'm probably missing something, but my file seems to conform with the example.
